const categories = {
  "folyadék": 1,
  "leves": 2,
  "gyümölcs": 3,
  "főétel": 4,
  "nassolnivaló": 5,
  "kenyérféle": 6,
  "köret": 7,
  "feltét": 8,
  "szósz": 9,
  "táplálék kieg.": 10,
  "zöldség": 11,
  "savanyúság": 12
}

const foodRecords = [{
  "name": "Alamalé Bravo 200ml",
  "category": 1,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 54,
  "carbohydrates": 0,
  "protein": 0,
  "fat": 12.8,
  "comment": "-"
},
{
  "name": "Alamaleves",
  "category": 2,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 53,
  "carbohydrates": 0.54,
  "protein": 1.6,
  "fat": 8.7,
  "comment": "-"
},
{
  "name": "Alma",
  "category": 3,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 50,
  "carbohydrates": 0.4,
  "protein": 0,
  "fat": 7,
  "comment": "-"
},
{
  "name": "Ananászos csirke ",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 288.6,
  "carbohydrates": 32.11,
  "protein": 13.14,
  "fat": 25.9,
  "comment": "-"
},
{
  "name": "Aranygaluska",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 266.4,
  "carbohydrates": 5.76,
  "protein": 10.2,
  "fat": 25,
  "comment": "-"
},
{
  "name": "Babapiskóta(Manner)",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 392,
  "carbohydrates": 9.5,
  "protein": 4.4,
  "fat": 78,
  "comment": "15dkg / adag"
},
{
  "name": "Bagett (Lipóti)",
  "category": 6,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 307,
  "carbohydrates": 9.1,
  "protein": 5.8,
  "fat": 53,
  "comment": "-"
},
{
  "name": "sajtos perec(Lipóti)",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 320,
  "carbohydrates": 12,
  "protein": 7.7,
  "fat": 50,
  "comment": "90g / adag"
},
{
  "name": "Banán",
  "category": 3,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 89.2,
  "carbohydrates": 1,
  "protein": 0.32,
  "fat": 24,
  "comment": "-"
},
{
  "name": "Bolognai spagetti",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 259.5,
  "carbohydrates": 13.7,
  "protein": 9.2,
  "fat": 29,
  "comment": "-"
},
{
  "name": "Brassói aprópecsenye(egytál)",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 234.8,
  "carbohydrates": 11.9,
  "protein": 7.7,
  "fat": 27.9,
  "comment": "-"
},
{
  "name": "Briós ",
  "category": 6,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 362,
  "carbohydrates": 7.5,
  "protein": 8.2,
  "fat": 63,
  "comment": "brunner"
},
{
  "name": "Brokkolikrémleves",
  "category": 2,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 86.8,
  "carbohydrates": 2.7,
  "protein": 5.8,
  "fat": 5.3,
  "comment": "-"
},
{
  "name": "Brokkolis, krémsajtos csirkemell",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 392.4,
  "carbohydrates": 39.9,
  "protein": 26.2,
  "fat": 7.4,
  "comment": "-"
},
{
  "name": "Bundászsemle",
  "category": 6,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 347.5,
  "carbohydrates": 9.3,
  "protein": 16.5,
  "fat": 35.6,
  "comment": "-"
},
{
  "name": "Burgonyakrokett(Avico)",
  "category": 7,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 170,
  "carbohydrates": 2.5,
  "protein": 5.5,
  "fat": 26.5,
  "comment": "-"
},
{
  "name": "Burgonyaleves",
  "category": 2,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 73.8,
  "carbohydrates": 1.6,
  "protein": 1.9,
  "fat": 10.9,
  "comment": "-"
},
{
  "name": "Burgonyapüré",
  "category": 7,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 146,
  "carbohydrates": 3.6,
  "protein": 4.6,
  "fat": 21.7,
  "comment": "-"
},
{
  "name": "Cézár saláta",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 209,
  "carbohydrates": 11.5,
  "protein": 15,
  "fat": 6.1,
  "comment": "-"
},
{
  "name": "Chili con carne",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 214.2,
  "carbohydrates": 14.3,
  "protein": 4.4,
  "fat": 26.2,
  "comment": "-"
},
{
  "name": "Chio chips",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 541,
  "carbohydrates": 5.5,
  "protein": 35,
  "fat": 48,
  "comment": "-"
},
{
  "name": "Csemege szalámi(pick)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 520,
  "carbohydrates": 24,
  "protein": 47,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Csirke nuggets 5db",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 257.2,
  "carbohydrates": 8.4,
  "protein": 14.7,
  "fat": 25.3,
  "comment": "-"
},
{
  "name": "Csirkemell pörkölt",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 159,
  "carbohydrates": 24.7,
  "protein": 5.2,
  "fat": 1.6,
  "comment": "-"
},
{
  "name": "Csirkepörkölt(comb)",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 171.2,
  "carbohydrates": 20.9,
  "protein": 10.6,
  "fat": 1.6,
  "comment": "-"
},
{
  "name": "Csoki, 3Bit",
  "category": 5,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 555,
  "carbohydrates": 5.3,
  "protein": 33.5,
  "fat": 57,
  "comment": "46g"
},
{
  "name": "Csoki( milka tej)",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 530,
  "carbohydrates": 6.3,
  "protein": 29,
  "fat": 59,
  "comment": "-"
},
{
  "name": "Csoki, Sportszelet",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 435,
  "carbohydrates": 4.2,
  "protein": 14.8387096774194,
  "fat": 68.5,
  "comment": "31g / adag"
},
{
  "name": "Csokis croassiantLipóti)",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 449,
  "carbohydrates": 7,
  "protein": 20,
  "fat": 59,
  "comment": "100g / adag"
},
{
  "name": "Csokis muffin",
  "category": 5,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 211,
  "carbohydrates": 3,
  "protein": 12,
  "fat": 22,
  "comment": "-"
},
{
  "name": "Csokisodó",
  "category": 9,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 97.3,
  "carbohydrates": 3.7,
  "protein": 2.2,
  "fat": 13,
  "comment": "-"
},
{
  "name": "Diben drink",
  "category": 10,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 300,
  "carbohydrates": 15,
  "protein": 14,
  "fat": 26.2,
  "comment": "200ml"
},
{
  "name": "Dzsem diabetikus Pacific",
  "category": 8,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 23,
  "carbohydrates": 0,
  "protein": 0,
  "fat": 4,
  "comment": "20g"
},
{
  "name": "Dzsem Pacific",
  "category": 8,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 66,
  "carbohydrates": 0,
  "protein": 0,
  "fat": 12,
  "comment": "25g"
},
{
  "name": "Eper",
  "category": 3,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 32,
  "carbohydrates": 1,
  "protein": 0,
  "fat": 7.2,
  "comment": "-"
},
{
  "name": "Étcsokoládé (Tibi)",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 487,
  "carbohydrates": 6.2,
  "protein": 27.8,
  "fat": 50.7,
  "comment": "-"
},
{
  "name": "Fonott kalács (Lavina)",
  "category": 6,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 347,
  "carbohydrates": 9.8,
  "protein": 5.6,
  "fat": 63,
  "comment": "-"
},
{
  "name": "Főtt tojás",
  "category": 8,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 66,
  "carbohydrates": 5.4,
  "protein": 4.8,
  "fat": 0,
  "comment": "44g"
},
{
  "name": "Füstölt kolbász(Kedvenc ízek)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 482,
  "carbohydrates": 18,
  "protein": 45,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Füstölt sonka(Pápai darabolt)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 218,
  "carbohydrates": 20,
  "protein": 15,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Fűszeres csirkecomb",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 167.786666666667,
  "carbohydrates": 20.9,
  "protein": 8.52666666666667,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Fűszeres csirkemell",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 159.333333333333,
  "carbohydrates": 24.7,
  "protein": 6.31333333333333,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Fűszeres húsgombóc",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 417.3,
  "carbohydrates": 21.8,
  "protein": 35.6,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Gabonapehely, kakaós, Nestlé",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 387,
  "carbohydrates": 9.6,
  "protein": 4.4,
  "fat": 73.6,
  "comment": "30g / adag"
},
{
  "name": "Galuska(Tante Fanny)",
  "category": 7,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 180,
  "carbohydrates": 5,
  "protein": 3,
  "fat": 35,
  "comment": "-"
},
{
  "name": "Gépsonka, Kedvenc ízek",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 141,
  "carbohydrates": 15.2,
  "protein": 6.5,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Görög saláta",
  "category": 7,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 72,
  "carbohydrates": 3.3,
  "protein": 4.6,
  "fat": 5,
  "comment": "-"
},
{
  "name": "Gyrostál",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 163.7,
  "carbohydrates": 8.6,
  "protein": 7.8,
  "fat": 13.8,
  "comment": "-"
},
{
  "name": "Gyümölcsleves",
  "category": 2,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 76.3,
  "carbohydrates": 0.6,
  "protein": 2,
  "fat": 13.3,
  "comment": "-"
},
{
  "name": "Holstein szelet",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 272.9,
  "carbohydrates": 24.9,
  "protein": 17.9,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Húsleves(hús nélkül)",
  "category": 2,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 19.9,
  "carbohydrates": 0.7,
  "protein": 0.13,
  "fat": 3.9,
  "comment": "-"
},
{
  "name": "Jégcsapretek",
  "category": 11,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 15,
  "carbohydrates": 1.2,
  "protein": 0.1,
  "fat": 1.2,
  "comment": "-"
},
{
  "name": "Joghurt, barackos Danone(125)",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 88,
  "carbohydrates": 3.8,
  "protein": 2.9,
  "fat": 11.8,
  "comment": "125g / adag"
},
{
  "name": "Joghurt, Danone Activia(125)",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 75,
  "carbohydrates": 4.9,
  "protein": 3.5,
  "fat": 6,
  "comment": "125g / adag"
},
{
  "name": "Joghurt, gyümölcsös, Napmintnap",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 76,
  "carbohydrates": 1.9,
  "protein": 1.2,
  "fat": 14.5,
  "comment": "110g / adag"
},
{
  "name": "Joghurt laktózmentes( Mizo 150)",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 62,
  "carbohydrates": 3.4,
  "protein": 3.6,
  "fat": 4,
  "comment": "150g / adag"
},
{
  "name": "Joghurt natúr( Nádudvari 150)",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 53,
  "carbohydrates": 3.2,
  "protein": 3,
  "fat": 2.8,
  "comment": "150g / adag"
},
{
  "name": "Kakaó(Mizo)",
  "category": 1,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 81,
  "carbohydrates": 2.8,
  "protein": 2.8,
  "fat": 11,
  "comment": "-"
},
{
  "name": "Kakaós csiga(Lipóti)",
  "category": 5,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 429,
  "carbohydrates": 6.9,
  "protein": 18,
  "fat": 58,
  "comment": "150g"
},
{
  "name": "Karfiolleves",
  "category": 2,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 68,
  "carbohydrates": 1.6,
  "protein": 3.9,
  "fat": 5.8,
  "comment": "-"
},
{
  "name": "Kefir (Nádudari 150)",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 59,
  "carbohydrates": 3.1,
  "protein": 3,
  "fat": 4.4,
  "comment": "150g / adag"
},
{
  "name": "Keksz háztartási győri",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 430,
  "carbohydrates": 7,
  "protein": 8.9,
  "fat": 79.5,
  "comment": "-"
},
{
  "name": "Keksz originalTuc",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 465,
  "carbohydrates": 8.3,
  "protein": 18.5,
  "fat": 65,
  "comment": "-"
},
{
  "name": "Kenőmájas(Kedvenc ízek)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 324,
  "carbohydrates": 15.4,
  "protein": 23,
  "fat": 0.3,
  "comment": "-"
},
{
  "name": "Kenyér",
  "category": 6,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 265,
  "carbohydrates": 10.1,
  "protein": 0.8,
  "fat": 54,
  "comment": "-"
},
{
  "name": "Ketchup(Globu Mindennapis)",
  "category": 9,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 110,
  "carbohydrates": 1.5,
  "protein": 0,
  "fat": 24,
  "comment": "15g / adag"
},
{
  "name": "KFC Longer szendvics",
  "category": 4,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 306,
  "carbohydrates": 11.8,
  "protein": 10,
  "fat": 42.3,
  "comment": "127g"
},
{
  "name": "KFC sült burgonya normál",
  "category": 7,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 268,
  "carbohydrates": 4.1,
  "protein": 11.6,
  "fat": 23.7,
  "comment": "105g"
},
{
  "name": "KFC sült csirke alsócomb",
  "category": 4,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 170,
  "carbohydrates": 15.9,
  "protein": 9.6,
  "fat": 5,
  "comment": "69g"
},
{
  "name": "Kifli ",
  "category": 6,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 166.1,
  "carbohydrates": 5.5,
  "protein": 2,
  "fat": 30,
  "comment": "-"
},
{
  "name": "Kinder tejszelet",
  "category": 5,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 118,
  "carbohydrates": 2.2,
  "protein": 7.8,
  "fat": 9.5,
  "comment": "28g"
},
{
  "name": "Kockasajt  (laktózmentes Medve)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 318,
  "carbohydrates": 12,
  "protein": 30,
  "fat": 0,
  "comment": "17,5g / adag"
},
{
  "name": "Kockasajt (Medve)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 246,
  "carbohydrates": 12,
  "protein": 20,
  "fat": 4.6,
  "comment": "17,5g / adag"
},
{
  "name": "Körettészta",
  "category": 7,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 146.2,
  "carbohydrates": 4.2,
  "protein": 3.4,
  "fat": 24.6,
  "comment": "-"
},
{
  "name": "Körözött (Nádudvari)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 151,
  "carbohydrates": 9.9,
  "protein": 10,
  "fat": 4.6,
  "comment": "-"
},
{
  "name": "Körte",
  "category": 3,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 57,
  "carbohydrates": 0.4,
  "protein": 0.2,
  "fat": 12.1,
  "comment": "-"
},
{
  "name": "Krémtúró, vaníliás (Milli)",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 171,
  "carbohydrates": 8.5,
  "protein": 5,
  "fat": 23,
  "comment": "90g / adag"
},
{
  "name": "Kukoricapehely (Nestlé)",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 381,
  "carbohydrates": 7.4,
  "protein": 1.4,
  "fat": 82.6,
  "comment": "30g / adag"
},
{
  "name": "Lapkasajt (Cheeseland)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 226.986666666667,
  "carbohydrates": 16,
  "protein": 14.9333333333333,
  "fat": 4.2,
  "comment": "18,75g / adag"
},
{
  "name": "Löncshús(Privát hús)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 216,
  "carbohydrates": 11,
  "protein": 18,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Májgaluskaleves",
  "category": 2,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 47.6,
  "carbohydrates": 2.1,
  "protein": 2.2,
  "fat": 4.6,
  "comment": "-"
},
{
  "name": "Májkrém (Szeged)",
  "category": 8,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 146.9,
  "carbohydrates": 6.5,
  "protein": 9.6,
  "fat": 8.4,
  "comment": "62g"
},
{
  "name": "Majonéz( Globus)",
  "category": 9,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 610,
  "carbohydrates": 0.7,
  "protein": 67,
  "fat": 4.5,
  "comment": "15g / adag"
},
{
  "name": "Majorannás burgonyafőzelék",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 163.652,
  "carbohydrates": 3.852,
  "protein": 4.632,
  "fat": 23,
  "comment": "-"
},
{
  "name": "Margarin mini (Flóra)",
  "category": 8,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 70.8,
  "carbohydrates": 0,
  "protein": 8,
  "fat": 0,
  "comment": "20g"
},
{
  "name": "Margarin mini(Risso)",
  "category": 8,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 22.6,
  "carbohydrates": 0,
  "protein": 2.5,
  "fat": 0,
  "comment": "10g"
},
{
  "name": "McDonald's hamburger",
  "category": 4,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 254,
  "carbohydrates": 13,
  "protein": 9,
  "fat": 30,
  "comment": "106g"
},
{
  "name": "McDonald's hamburger csirke",
  "category": 4,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 347,
  "carbohydrates": 11,
  "protein": 16,
  "fat": 38,
  "comment": "133g"
},
{
  "name": "McDonald's sült burgonya",
  "category": 7,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 231,
  "carbohydrates": 3,
  "protein": 11,
  "fat": 29,
  "comment": "80g"
},
{
  "name": "Meggymártás",
  "category": 4,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 138.4,
  "carbohydrates": 1.55,
  "protein": 2.5,
  "fat": 25.6,
  "comment": "-"
},
{
  "name": "Mexikói saláta",
  "category": 7,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 170,
  "carbohydrates": 4.3,
  "protein": 9.8,
  "fat": 14.9,
  "comment": "-"
},
{
  "name": "Méz diabetikus Pacific ",
  "category": 8,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 67.4,
  "carbohydrates": 0,
  "protein": 0,
  "fat": 16.6,
  "comment": "20g"
},
{
  "name": "Méz mini ",
  "category": 8,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 90.5,
  "carbohydrates": 0,
  "protein": 0,
  "fat": 21,
  "comment": "25g"
},
{
  "name": "Mogyorókrém Miss Nuss",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 550,
  "carbohydrates": 2.3,
  "protein": 33,
  "fat": 61,
  "comment": "-"
},
{
  "name": "Mustár(Globus)",
  "category": 9,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 110,
  "carbohydrates": 5,
  "protein": 6,
  "fat": 9,
  "comment": "-"
},
{
  "name": "Mustáros csirkemell",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 205.2,
  "carbohydrates": 26.3,
  "protein": 8.6,
  "fat": 4.3,
  "comment": "-"
},
{
  "name": "Müzli meggyes Cerbona ",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 400,
  "carbohydrates": 6.7,
  "protein": 10,
  "fat": 69.3,
  "comment": "40g / adag"
},
{
  "name": "Müzli szelet(cini minis )",
  "category": 5,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 102,
  "carbohydrates": 1.8,
  "protein": 3.3,
  "fat": 15.2,
  "comment": "25g"
},
{
  "name": "Narancs",
  "category": 3,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 40,
  "carbohydrates": 0.9,
  "protein": 0,
  "fat": 9.4,
  "comment": "-"
},
{
  "name": "Natúr csirkemell fűszeres",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 348,
  "carbohydrates": 6,
  "protein": 5,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Nudli, cukorral és barackízzel",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 278.664,
  "carbohydrates": 4.8,
  "protein": 4.064,
  "fat": 90.7,
  "comment": "-"
},
{
  "name": "Nutella",
  "category": 8,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 80,
  "carbohydrates": 0.9,
  "protein": 4.6,
  "fat": 8.6,
  "comment": "15g"
},
{
  "name": "Nutridrink",
  "category": 10,
  "refAmount": 1,
  "refUnit": "adag",
  "portionMultiplier": 1.0,
  "energy": 300,
  "carbohydrates": 12,
  "protein": 11.4,
  "fat": 36.8,
  "comment": "-"
},
{
  "name": "Nutridrink Max",
  "category": 10,
  "refAmount": 1,
  "refUnit": "adag",
  "portionMultiplier": 1.0,
  "energy": 720,
  "carbohydrates": 28.8,
  "protein": 27.3,
  "fat": 89.1,
  "comment": "-"
},
{
  "name": "pufasztott kukorica",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 386,
  "carbohydrates": 9,
  "protein": 1,
  "fat": 86,
  "comment": "-"
},
{
  "name": "Olasz felvágott(Kométa)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 272,
  "carbohydrates": 12,
  "protein": 24,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Orosz hússaláta",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 307.2,
  "carbohydrates": 9,
  "protein": 19.1,
  "fat": 23.9,
  "comment": "-"
},
{
  "name": "Őszibarack",
  "category": 3,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 40,
  "carbohydrates": 1,
  "protein": 0,
  "fat": 9,
  "comment": "-"
},
{
  "name": "Őszibarack krémleves",
  "category": 2,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 114,
  "carbohydrates": 0.7,
  "protein": 2.1,
  "fat": 23,
  "comment": "-"
},
{
  "name": "Padlizsánkrém majonézes(kenni jó)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 232,
  "carbohydrates": 1.2,
  "protein": 21,
  "fat": 9,
  "comment": "-"
},
{
  "name": "Palacsinta ízes",
  "category": 5,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 177.4,
  "carbohydrates": 5.2,
  "protein": 2.1,
  "fat": 34,
  "comment": "-"
},
{
  "name": "Palacsinta  kakaós",
  "category": 5,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 177.4,
  "carbohydrates": 5.2,
  "protein": 2.1,
  "fat": 34,
  "comment": "-"
},
{
  "name": "Paprikás burgonya kolbásszal",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 213.7,
  "carbohydrates": 6.8,
  "protein": 10.4,
  "fat": 20.7,
  "comment": "-"
},
{
  "name": "Paprikás szalámi(Privát hús)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 441,
  "carbohydrates": 19,
  "protein": 40,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Paradicsom",
  "category": 11,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 22,
  "carbohydrates": 1,
  "protein": 0.2,
  "fat": 0.4,
  "comment": "-"
},
{
  "name": "Paradicsomleves",
  "category": 2,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 84.1,
  "carbohydrates": 0.6,
  "protein": 1.7,
  "fat": 14.6,
  "comment": "-"
},
{
  "name": "Paradicsomos káposzta",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 113.2,
  "carbohydrates": 0.6,
  "protein": 2.76,
  "fat": 17.8,
  "comment": "-"
},
{
  "name": "Paradicsomsaláta",
  "category": 12,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 90.2,
  "carbohydrates": 0,
  "protein": 6.6,
  "fat": 5.6,
  "comment": "-"
},
{
  "name": "Parizer (Finomino)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 235,
  "carbohydrates": 10,
  "protein": 21.1,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Párolt marhaszelet",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 116,
  "carbohydrates": 20.6,
  "protein": 3.4,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Párolt zöldség(brokkoli, zöldborsó, s.répa)",
  "category": 7,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 78.9,
  "carbohydrates": 3.2,
  "protein": 0.375,
  "fat": 9.8,
  "comment": "-"
},
{
  "name": "Petrezselymes burgonya",
  "category": 7,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 132,
  "carbohydrates": 2.5,
  "protein": 4.3,
  "fat": 20,
  "comment": "-"
},
{
  "name": "Pincepörkölt",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 199.2,
  "carbohydrates": 12.3,
  "protein": 6,
  "fat": 20,
  "comment": "-"
},
{
  "name": "Pogácsa (Bombajóó)",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 335,
  "carbohydrates": 7.9,
  "protein": 17.4,
  "fat": 36.1,
  "comment": "-"
},
{
  "name": "Pudding ( Danette csokis )",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 122.4,
  "carbohydrates": 3.3,
  "protein": 3.04,
  "fat": 19.9,
  "comment": "125g / adag"
},
{
  "name": "Pulykasonka(Kedvenc ízek)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 148,
  "carbohydrates": 12,
  "protein": 10,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Rakott burgonya",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 296.9,
  "carbohydrates": 9.1,
  "protein": 16,
  "fat": 26.8,
  "comment": "-"
},
{
  "name": "Rakott kelkáposzta",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 166.6,
  "carbohydrates": 12.5,
  "protein": 7,
  "fat": 11.3,
  "comment": "-"
},
{
  "name": "Rántott csirke comb",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 245,
  "carbohydrates": 26,
  "protein": 14.9,
  "fat": 15,
  "comment": "-"
},
{
  "name": "Rántott csirkemell",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 235,
  "carbohydrates": 31.6,
  "protein": 14.9,
  "fat": 15,
  "comment": "-"
},
{
  "name": "Rántott gomba",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 204,
  "carbohydrates": 2.875,
  "protein": 14.9,
  "fat": 13.5,
  "comment": "-"
},
{
  "name": "Rántott szelet",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 255,
  "carbohydrates": 26.8,
  "protein": 14.9,
  "fat": 15,
  "comment": "-"
},
{
  "name": "Rizi-bizi",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 148.1,
  "carbohydrates": 3.9,
  "protein": 3.2,
  "fat": 21,
  "comment": "-"
},
{
  "name": "Rizs  kukoricás",
  "category": 7,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 157.3,
  "carbohydrates": 3.4,
  "protein": 3.2,
  "fat": 27.4,
  "comment": "-"
},
{
  "name": "Rizs  párolt",
  "category": 7,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 128.2,
  "carbohydrates": 2.4,
  "protein": 2.6,
  "fat": 25,
  "comment": "-"
},
{
  "name": "Rizseshús",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 165.1,
  "carbohydrates": 7.2,
  "protein": 4.7,
  "fat": 22,
  "comment": "-"
},
{
  "name": "Rizsfelfújt",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 219.3,
  "carbohydrates": 6.68,
  "protein": 5.2,
  "fat": 30,
  "comment": "-"
},
{
  "name": "Sajt trappista(Tolle)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 341,
  "carbohydrates": 25.5,
  "protein": 26,
  "fat": 0.2,
  "comment": "-"
},
{
  "name": "Sajt laktózmentes ( Mizo)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 318,
  "carbohydrates": 24,
  "protein": 24,
  "fat": 2,
  "comment": "-"
},
{
  "name": "Sajtkrém( Tolle)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 273,
  "carbohydrates": 12.3,
  "protein": 24.4,
  "fat": 0.6,
  "comment": "-"
},
{
  "name": "Savanyú uborka(Bonduelle)",
  "category": 12,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 28,
  "carbohydrates": 1.2,
  "protein": 0.1,
  "fat": 4.6,
  "comment": "-"
},
{
  "name": "Sertéspörkölt",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 262.9,
  "carbohydrates": 21,
  "protein": 12.8,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Sertészsír",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 928,
  "carbohydrates": 0,
  "protein": 100,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Sós burgonya",
  "category": 7,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 92,
  "carbohydrates": 2.5,
  "protein": 0.2,
  "fat": 20,
  "comment": "-"
},
{
  "name": "Spagetti carbonara",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 311.7,
  "carbohydrates": 11.8,
  "protein": 16.1,
  "fat": 29.5,
  "comment": "-"
},
{
  "name": "Sprotni (füstölt Golden Globe Riga)",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 356,
  "carbohydrates": 17,
  "protein": 32,
  "fat": 0,
  "comment": "160g / adag"
},
{
  "name": "Sült burgonya  tepsiben",
  "category": 7,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 128,
  "carbohydrates": 2.5,
  "protein": 3.3,
  "fat": 20,
  "comment": "-"
},
{
  "name": "Sült csirkeszárny",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 201.960784313725,
  "carbohydrates": 21.9607843137255,
  "protein": 12.5490196078431,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Sült sertés tarja",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 266,
  "carbohydrates": 21.6,
  "protein": 18.7,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Sült sonka (Kométa)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 103,
  "carbohydrates": 17.96875,
  "protein": 3,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Sült szalonna",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 619.833333333333,
  "carbohydrates": 18,
  "protein": 61.9166666666667,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Süti, dobostorta",
  "category": 5,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 293.6,
  "carbohydrates": 4.7,
  "protein": 13.7,
  "fat": 37.8,
  "comment": "-"
},
{
  "name": "Süti, krémes",
  "category": 5,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 340,
  "carbohydrates": 5.4,
  "protein": 16,
  "fat": 42.8,
  "comment": "-"
},
{
  "name": "Süti, meggyes-mákos pite",
  "category": 5,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 619,
  "carbohydrates": 9.9,
  "protein": 27.1,
  "fat": 81.5,
  "comment": "-"
},
{
  "name": "Szafaládé( Wiesbauer)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 262,
  "carbohydrates": 13,
  "protein": 23,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Tarhonyás hús",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 196.5,
  "carbohydrates": 11.6,
  "protein": 6.1,
  "fat": 28,
  "comment": "-"
},
{
  "name": "Tartármártás",
  "category": 9,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 627.6,
  "carbohydrates": 2.8,
  "protein": 66.4,
  "fat": 6,
  "comment": "-"
},
{
  "name": "Tavaszi rizs",
  "category": 7,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 146.2,
  "carbohydrates": 3.18,
  "protein": 3.19,
  "fat": 25.4,
  "comment": "-"
},
{
  "name": "Teavaj(magyar)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 745,
  "carbohydrates": 0.4,
  "protein": 82,
  "fat": 0.5,
  "comment": "-"
},
{
  "name": "Tej 2,8%  (Mizo)",
  "category": 1,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 56,
  "carbohydrates": 3,
  "protein": 2.8,
  "fat": 4.7,
  "comment": "-"
},
{
  "name": "Tejberizs(Müller)",
  "category": 5,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 108,
  "carbohydrates": 3.3,
  "protein": 2.2,
  "fat": 16.8,
  "comment": "-"
},
{
  "name": "Tejeskávé (Mizo)",
  "category": 1,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 79,
  "carbohydrates": 2.8,
  "protein": 3.3,
  "fat": 9.2,
  "comment": "-"
},
{
  "name": "Tejfölös szelet",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 256.4,
  "carbohydrates": 18.3,
  "protein": 17.5,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Téliszalámi (Kométa)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 515,
  "carbohydrates": 23,
  "protein": 47,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Tepertő",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 823,
  "carbohydrates": 12,
  "protein": 83,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Tihany camembert Szendvics",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 291,
  "carbohydrates": 20,
  "protein": 23,
  "fat": 1,
  "comment": "-"
},
{
  "name": "Tiramisu",
  "category": 5,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 334.2,
  "carbohydrates": 8.8,
  "protein": 7.7,
  "fat": 57,
  "comment": "-"
},
{
  "name": "Tojásleves",
  "category": 2,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 44.3,
  "carbohydrates": 1.2,
  "protein": 2.9,
  "fat": 2.9,
  "comment": "-"
},
{
  "name": "Tojásrántotta(2db)",
  "category": 8,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 178.2,
  "carbohydrates": 10.8,
  "protein": 14.6,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Töltött paprika",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 137.1,
  "carbohydrates": 7.2,
  "protein": 4.6,
  "fat": 17.5,
  "comment": "-"
},
{
  "name": "Turista felvágott(Zimbo)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 384,
  "carbohydrates": 17,
  "protein": 35,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Túró rudi óriás, Pöttyös ",
  "category": 5,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 182,
  "carbohydrates": 4.9,
  "protein": 9.1,
  "fat": 19.9,
  "comment": "51g"
},
{
  "name": "Túró rudi Pöttyös ",
  "category": 5,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 107,
  "carbohydrates": 2.9,
  "protein": 5.3,
  "fat": 12,
  "comment": "30g"
},
{
  "name": "Túró ( Nádudvari)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 137,
  "carbohydrates": 16.32,
  "protein": 7,
  "fat": 2,
  "comment": "-"
},
{
  "name": "Uborka",
  "category": 11,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 11,
  "carbohydrates": 1,
  "protein": 0.1,
  "fat": 1.7,
  "comment": "-"
},
{
  "name": "Uborkasaláta",
  "category": 12,
  "refAmount": 15,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 56.5,
  "carbohydrates": 1.5,
  "protein": 0,
  "fat": 12.5,
  "comment": "-"
},
{
  "name": "Uborkasaláta, tejfölös",
  "category": 12,
  "refAmount": 15,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 91.1,
  "carbohydrates": 2.26,
  "protein": 3.2,
  "fat": 13.3,
  "comment": "-"
},
{
  "name": "Vagdalt pogácsa",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 291,
  "carbohydrates": 21,
  "protein": 16,
  "fat": 15.9,
  "comment": "-"
},
{
  "name": "Vagdalt egyben",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 276,
  "carbohydrates": 20.8,
  "protein": 14.8,
  "fat": 14.9,
  "comment": "-"
},
{
  "name": "Vajkrém (Nádudvari)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 384,
  "carbohydrates": 4.7,
  "protein": 39,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Vegyes savanyúság(Gloster)",
  "category": 12,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 15,
  "carbohydrates": 0.8,
  "protein": 0.1,
  "fat": 2.4,
  "comment": "-"
},
{
  "name": "Virsli (Privát hús)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 197,
  "carbohydrates": 11,
  "protein": 16,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Zala felvágott ( Kedvenc ízek)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 224,
  "carbohydrates": 13,
  "protein": 18,
  "fat": 0,
  "comment": "-"
},
{
  "name": "Zellerkrémleves",
  "category": 2,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 64.8,
  "carbohydrates": 1.6,
  "protein": 3.4,
  "fat": 6.5,
  "comment": "-"
},
{
  "name": "Zöldborsóleves",
  "category": 2,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 48.1,
  "carbohydrates": 1.5,
  "protein": 2.1,
  "fat": 5.3,
  "comment": "-"
},
{
  "name": "Zöldborsós sertésszelet",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 230.2,
  "carbohydrates": 19.5,
  "protein": 11.5,
  "fat": 11.5,
  "comment": "-"
},
{
  "name": "Zöldpaprika",
  "category": 11,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 20,
  "carbohydrates": 1.2,
  "protein": 0.3,
  "fat": 3,
  "comment": ""
},
{
  "name": "Zöldsaláta tejfölös öntettel",
  "category": 7,
  "refAmount": 25,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 413.4,
  "carbohydrates": 3.9,
  "protein": 33.7,
  "fat": 16.4,
  "comment": "-"
},
{
  "name": "Zöldséges párolt bulgur",
  "category": 4,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 145.4,
  "carbohydrates": 4.4,
  "protein": 3.6,
  "fat": 24.9,
  "comment": "-"
},
{
  "name": "Zöldségkrémleves",
  "category": 2,
  "refAmount": 1,
  "refUnit": "dl",
  "portionMultiplier": 1.0,
  "energy": 71.3,
  "carbohydrates": 1,
  "protein": 4.8,
  "fat": 5.4,
  "comment": "-"
},
{
  "name": "Zsemle",
  "category": 6,
  "refAmount": 1,
  "refUnit": "db",
  "portionMultiplier": 1.0,
  "energy": 147,
  "carbohydrates": 5.1,
  "protein": 0.4,
  "fat": 33,
  "comment": "5,5dkg"
},
{
  "name": "Tejföl (Mizo 20%)",
  "category": 8,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 204,
  "carbohydrates": 2.8,
  "protein": 20,
  "fat": 3.2,
  "comment": "-"
},
{
  "name": "Sült hasábburgonya",
  "category": 7,
  "refAmount": 10,
  "refUnit": "dkg",
  "portionMultiplier": 1.0,
  "energy": 120,
  "carbohydrates": 11,
  "protein": 2,
  "fat": 19.5,
  "comment": "-"
}];

const meals = [{
  id: 'reggeli-1',
  name: 'Reggeli',
  portions: [
    {food: JSON.parse(JSON.stringify(foodRecords[0])), qty: 1.5},
    {food: JSON.parse(JSON.stringify(foodRecords[1])), qty: 1.78}
  ],
  limits: {
    energy: 3000,
    carbohydrates: 10,
    fat: 50,
    protein: {min: 10, max: 100}
  }
},
{
  id: 'ebed-1',
  name: 'Ebéd',
  portions: [
    {food: JSON.parse(JSON.stringify(foodRecords[2])), qty: 0.5},
    {food: JSON.parse(JSON.stringify(foodRecords[3])), qty: 2}
  ],
  limits: {
    energy: 3000,
    carbohydrates: 10,
    fat: 50,
    protein: {min: 10, max: 100}
  },
},
{
  id: 'vacsora-1',
  name: 'Vacsora',
  portions: [
    {food: JSON.parse(JSON.stringify(foodRecords[4])), qty: 1},
    {food: JSON.parse(JSON.stringify(foodRecords[5])), qty: 1.5}
  ],
  limits: {
    energy: 3000,
    carbohydrates: 10,
    fat: 50,
    protein: {min: 10, max: 100}
  },
}]

export {
  categories,
  foodRecords,
  meals
}
